name = "emuskin-images-worker"
main = "src/index.js"
compatibility_date = "2024-01-01"
account_id = "ca0643bf4603e2211f4e3ba63b608e8c"

# R2 bucket binding
[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "emuskin-images"
preview_bucket_name = "emuskin-images-dev"

# Environment variables
[vars]
ALLOWED_ORIGINS = "http://localhost:3000,http://localhost:8008,http://localhost:5173,https://emuskin.playcase.gg"
MAX_FILE_SIZE = "10485760" # 10MB in bytes

# KV namespace for storing image metadata (optional)
[[kv_namespaces]]
binding = "IMAGE_METADATA"
id = "bed8def46d4b489c8ceeaf96a0c6be0e"
preview_id = "78695ef32ae840479bfd16408ecaad96"