# Render deployment configuration
services:
  - type: web
    name: emuskin-api
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false # Set in dashboard
      - key: ALLOWED_ORIGINS
        sync: false # Set in dashboard